const teams = [
    new Time('Internacional', 'assets/internacional.png'),
    new Time('Grêmio', 'assets/gremio.png'),
    new Time('Santos', 'assets/santos.png'),
    new Time('São Paulo', 'assets/sao_paulo.png'),
    new Time('América MG', 'assets/america_mg.png'),
    new Time('Atlético MG', 'assets/atletico_mg.png'),
    new Time('Atlético PR', 'assets/atletico_pr.png'),
    new Time('Vasco', 'assets/vasco.png'),
    new Time('Botafogo', 'assets/botafogo.png'),
    new Time('Flamengo', 'assets/flamengo.png'),
    new Time('Fluminense', 'assets/fluminense.png'),
    new Time('Corinthians', 'assets/corinthians.png'),
    new Time('Palmeiras', 'assets/palmeiras.png'),
    new Time('Bahia', 'assets/bahia.png'),
    new Time('Ceará', 'assets/ceara.png'),
    new Time('Chapecoense', 'assets/chapecoense.png'),
    new Time('Cruzeiro', 'assets/cruzeiro.png'),
    new Time('Paraná', 'assets/parana.png'),
    new Time('Sport', 'assets/sport.png'),
    new Time('Vitória', 'assets/vitoria.png')
]